config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/zmkm', as: 'rails_admin'
  resources :notifications

  resource :notification_setting
  get '/:id' => 'votes#show_by_token', id: /[a-zA-Z0-9]{6}/, as: :token
  resources :votes do
    get :created_success, on: :member
    post :praise, on: :member
    get :hot, on: :collection
    get :done, on: :collection
    resources :vote_items
    get :lucky, on: :collection

    #resources :questions
    get :result, on: :member
    match :search, on: :collection, via: [:get, :post]

    # 三种不同类型的新建表单
    # 普通议题，购物分享，引用点评
    get :new_common,   on: :collection
    get :new_shopping, on: :collection
    get :new_quote,  on: :collection
  end
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  root 'home#index'

  get '/account' => 'account#index'
  get '/account/created_votes' => 'account#created_votes'
  get '/account/joined_votes' => 'account#joined_votes'
  get '/account/notification_setting' => 'account#notification_setting'
  get '/account/feedback'     => 'account#feedback'
  get '/account/about'     => 'account#about'
  get '/account/info'      => 'account#info'
  resources :feedbacks

  resources :infocards do
    get :parse_url, on: :collection
  end
end

app/models/vote.rb
class Vote
  include Mongoid::Document
  include Mongoid::Timestamps
  # for search
  include VoteSearchConfig
  
  include Infocard::VoteMethods

  field :title, type: String
  field :finish_at, type: Time#, default: ->{ 7.days.from_now }
  field :token, type: String
  field :url, type: String
  # 创建当周的第一天,用于排序
  field :first_day, type: String, default: -> { Time.now.beginning_of_week.strftime '%Y%m%d' }
  field :voted_users_count, type: Integer, default: 0

  belongs_to :user, inverse_of: :votes
  has_many :vote_items
  has_and_belongs_to_many :voted_users, class_name: 'User', inverse_of: :voted_votes
  # todo images
  # has_many images

  accepts_nested_attributes_for :vote_items, :reject_if => :all_blank, :allow_destroy => true

  validates_presence_of :title
  #validates_presence_of :finish_at
  validates :token,    uniqueness: true,    presence: true

  scope :recent, -> { desc(:id) }
  scope :hot, -> { desc(:first_day, :voted_users_count).recent}
  scope :not_finished, -> { where(:finish_at.gt => Time.now) }
  scope :not_voted, -> (user) { where({:voted_user_ids.nin => [user.id]}) }
  #scope :by_user, -> (user) { any_of({:user_id => user.id}, {:user_ids.in => [user.id]}, {:invite_uids.in => [user.uid]}) }


  def self.parse(token)
    Vote.where(token: token).first
  end

  def finished?
    Time.now > finish_at.end_of_day
  end

  def build_uniq_token_if_blank
    until !self.token.blank?
      tmp = randstr
      self.token = tmp unless Vote.where(token: tmp).first
    end
  end

  def vote_items_count
    vote_items.count
  end

  def praised_count
    vote_items.to_a.sum{|vote_item| vote_item.praised_count }
  end

  def added_vote_item_by? user
    vote_items.any?{|vote_item| vote_item.user == user and vote_item.is_extra and !vote_item.new_record?}
  end

  def self.rand_next user
    n = (0..not_voted(user).count-1).to_a.sample
    not_voted(user).skip(n).first
  end

  # 根据不同的用户返回不同的 vote_items 排列顺序
  def vote_items_rand_order_by_user user
    user_ord = (user.created_at.to_i % 43) + 1 
    # 43是随便取的一个素数，
    # 可以随意换个大于选项个数的2~3位的数字代替, 
    # +1为使之不为0
    vote_items.sort {|x, y| 
      (x.ord % user_ord) <=> (y.ord % user_ord)
    }
  end

  # 判断是否被指定 user 投票过
  def has_voted_by?(user)
    voted_users.include? user
  end

  protected
  before_create :fill_vote_items_user
  def fill_vote_items_user
    vote_items.each do |vote_item|
      vote_item.user = self.user
    end
  end

  before_validation :init_token
  def init_token
    build_uniq_token_if_blank if self.token.blank?
  end

  def randstr(length=6)
    base = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
    size = base.size
    re = '' << base[rand(size-10)]
    (length - 1).times {
      re << base[rand(size)]
    }
    re
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  layout :choose_layout
  before_filter :authenticate_user!, except: [:show_by_token]
  before_action :set_vote, only: [:edit, :destroy]

  respond_to :html
  respond_to :json, only: [:index, :hot]
  respond_to :js, only: [:new, :create]

  def index
    @votes = Vote.recent.page(params[:page]).per(10)
  end

  def hot
    @votes = Vote.hot.page(params[:page]).per(10)
    render :index
  end

  def show
    @vote = Vote.find params[:id]
    @vote_items = @vote.vote_items_rand_order_by_user current_user
    session[:lucky] = @vote.id.to_s
  end

  # !!R
  # def new
  #   @vote = current_user.votes.new
  #   case params[:kind]
  #   when 'text'
  #     respond_with(@vote)
  #   when 'comment'
  #     render :new_with_comment
  #   when 'weburl'
  #     _new_with_weburl
  #   end
  # end

  # def _new_with_weburl
  #   return render :new_with_weburl_select_category if params[:category_id].blank?

  #   if params[:infocard_id].blank?
  #     @category = InfocardAppCategory.find(params[:category_id])
  #     return render :new_with_weburl_select_infocard
  #   end

  #   @category = InfocardAppCategory.find(params[:category_id])
  #   @infocard = Infocard.find(params[:infocard_id])
  #   render :new_with_weburl_by_infocard
  # end

  # 创建普通议题
  def new_common
    @vote = current_user.votes.new
  end

  # 创建购物点评
  def new_shopping
    @vote = current_user.votes.new
  end

  # 创建引用分享
  def new_quote
    @vote = current_user.votes.new
  end


  def created_success
    @vote = current_user.votes.find params[:id]
  end

  def edit
    if @vote.finished?
      redirect_to result_vote_path(@vote), alert: '议题已经过期'
    end
  end

  def create
    @vote = current_user.votes.new(vote_params)
    if @vote.save
      redirect_to "/votes/#{@vote.id}/created_success"
    else
      render :new
    end
  end

  def update
    @vote = Vote.find params[:id]
    user_ids = @vote.voted_users.map(&:id)
    
    if @vote.update(vote_params) and @vote.user == current_user and @vote.shares.un_shared.any?
      redirect_to @vote.shares.un_shared.last
    else
      respond_with(@vote)
    end
  end

  def result
    @vote = Vote.find params[:id]
    @questions = @vote.questions.includes(:answers)
  end

  def show_by_token
    @vote = Vote.where(token: params[:id]).first
    if current_user
      unless @vote.invite_uids.include?(current_user.uid)
        @vote.invite_uids << current_user.uid
        @vote.save
      end
      redirect_to @vote
    end
  end

  def search
    if !params[:q].blank?
      vote_result = Vote.page_search(params[:q], params[:page])
      @votes = vote_result.map{|vote_info|Vote.find(vote_info["_id"])}
    else
      @votes = []
    end
    respond_to do |format|
      format.html
      format.json do 
        vote_json = @votes.map do |vote|
          {
            :id    => vote.id.to_s,
            :title => vote.title.gsub(Regexp.new(params[:q]), '<span class="key">\0</span>'),
            :voted_users_count => vote.voted_users_count,
            :vote_items_count  => vote.vote_items_count
          }
        end
        render :json => vote_json
      end
    end
  end

  def praise
    @vote = Vote.find params[:id]
    @vote_items = @vote.vote_items
    @praise_vote_items = @vote_items.find params[:vote_item_ids]
    @praise_vote_items.map{|vote_item| vote_item.praise_by current_user}
    @vote_items.where(:id.nin => params[:vote_item_ids]).map{|vote_item| vote_item.cancel_praise_by(current_user)}
    # 做改变即操作即可，出错则直接报错，无需处理
    render json: true
  end

  # 随机获取一个未投票的议题
  def lucky
    return if not request.xhr?

    vote = Vote.rand_next current_user
    if vote.present?
      render :json => {
        :id => vote.id.to_s
      }
    else
      render :status => 404
    end
  end

  private
  def set_vote
    @vote = current_user.votes.find(params[:id])
  end

  def vote_params
    params.require(:vote).permit(:infocard_id, :title, :url, vote_items_attributes: [:id, :title])
  end

  def choose_layout
    return 'detail' if %w(new_common new_shoping new_quote).include? action_name
    return 'app'
  end
end

app/views/votes/_create.html.haml
$('#messages').prepend('#{j render "layouts/message", name: 'notice', msg: "您被“#{@vote.user.nickname}”邀请参加投票：" + @vote.title}')
$('#votes').prepend('
.vote{:id => "#{@vote.id}"}>= j render @vote
')

app/views/votes/_form.html.erb
<%= simple_form_for @vote, wrapper: :horizontal_form do |f| %>
  <% disabled = (!f.object.new_record? and f.object.answered?) %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title text-center">编辑新议题</h3>
    </div>
    <div class="panel-body">
      <%= f.input :title, disabled: disabled %>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title text-center">讨论要点 <%= link_to_add_association '+ 增加一个要点', f, :questions, 'class' => 'btn btn-default', 'data-association-insertion-node' => '#div-vote-questions' %></h3>
    </div>
    <div class="panel-body">
      <div id="div-vote-questions" class="">
        <%= f.simple_fields_for :questions do |question| %>
          <%= render "question_fields", :f => question %>
        <% end -%>
      </div>
      <%= f.input :finish_at, as: :date_picker %>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title text-center">邀请微博好友参与讨论 <button id="wb_selector" type="button" class="btn btn-primary">+ 添加好友</button></h3>
    </div>
    <div class="panel-body">
      <strong>已邀请好友：</strong>
      <div class="div-invited-uids">
        <% @vote.invite_uids.each do |invite_uid| %>
          <input class="hidden" type="checkbox" value="<%= invite_uid %>" checked="checked" name="vote[invite_uids][]" id="vote_invite_uids_<%= invite_uid %>"><%= @vote.user.friendships.where(uid: invite_uid).first.try(:name) %>
        <% end -%>
      </div>
      <hr />
      <strong>此次邀请好友：</strong>
      <div class="div-invite-uids">
        <%#= f.collection_check_boxes(:invite_uids, current_user.friendships, :uid, :name){|b| b.label(:"data-value" => b.value) { selected=f.object.invite_uids.include?(b.object.uid.to_s); b.check_box(checked: selected, class: (selected ?'hidden' : '') ) + b.text }  } %>
      </div>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, @vote.new_record? ? '发布新议题' : '修改议题', class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

<script type="text/javascript">
  $(document).on('ready page:change', function() {
    $('.date_picker.vote_finish_at').datetimepicker({
      language: 'zh-CN',
      pickTime: false
    });

    WB2.anyWhere(function(W){
      W.widget.selector({
        id : "wb_selector",
        tab: {list: [1],index: 1},
        callback: function(data) {
          var jsonStr = JSON.stringify(data, null, '\t');
          $.each(data, function(e){
            var uid = (Number)(this.id);
            if($('#vote_invite_uids_' + this.id).length == 0){
              $.post('/friendships', {friendship: {uid: uid, name: this.screen_name}});
              $('.div-invite-uids').append('<span><label for="vote_invite_uids_' + this.id + '"><label data-value="' + this.id + '" for="vote_invite_uids_' + this.id + '"><input class="" type="checkbox" value="' + this.id + '" name="vote[invite_uids][]" id="vote_invite_uids_' + this.id + '" checked="checked">' + this.screen_name + '</label></label></span>');
            }
          });
        }
      });
    });
  });
</script>

app/views/votes/_show_form.html.haml
= simple_form_for vote do |f|
  .questions
    = f.simple_fields_for :questions do |question|
      .question
        .answers
          .panel.panel-default
            .panel-heading
              %h3.panel-title.text-center
                讨论要点：#{question.object.title}
            .panel-body
              - if question.object.answered_by? current_user
                .row
                  - question.object.answers.each do |answer|
                    .col-xs-1.col-xs-offset-3
                      - if answer.answered_by? current_user
                        %span.glyphicon.glyphicon-ok
                    .col-sm-8
                      = answer.title
              - else
                .row{:style => "position: relative;"}
                  .col-xs-offset-4.col-xs-8
                    .row
                      = question.simple_fields_for :answers do |answer|
                        = render "votes/show_form_answer_fields", f: answer
                      %div
                        = link_to_add_association '+ 补充一个选项', question, :answers, class: 'btn btn-default col-xs-offset-7 col-xs-5 btn-vote-question-add-answer', style: 'position: absolute;', partial: 'votes/show_form_answer_fields'
        = question.input :id, as: :hidden
  .form-actions
    %button.btn.btn-default.btn-block{"data-target" => "#myModal", "data-toggle" => "modal", :onclick => "return false;", :type => "button"} + 增加一个讨论要点
    - if !vote.finished? and vote.user == current_user
      = link_to '发起人修改议题', edit_vote_path(vote), class: 'btn btn-default btn-block'
    = f.button :submit, '贡献我的想法', class: 'btn btn-primary btn-block'

app/views/votes/_show_form_disabled.html.erb
<%= simple_form_for vote, html: {onsubmit: 'return false;'} do |f| %>
  <div class="questions">
    <%= f.simple_fields_for :questions do |question| %>
      <div class="question">
        <div class="answers">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title text-center">讨论要点：<%= question.object.title %></h3>
            </div>
            <div class="panel-body">
              <div class="row" style="position: relative;">
                <div class="col-xs-offset-4 col-xs-8">
                  <div class="row">
                    <%= question.simple_fields_for :answers do |answer| %>
                    <div class="answer col-xs-7">
                      <%= answer.input :voter_id, as: :boolean, label: false, inline_label: answer.object.try(:title) || answer.input(:title, wrapper: :inline_form), checked_value: nil, unchecked_value: nil, disabled: true %>
                    </div>
                    <% end -%>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end -%>
  </div>
<% end %>

app/views/votes/created_success.html.haml
.page-created
  .title
    %span 议题创建成功

  .desc 现在你可以去给自己的议题投票
  .go
    = link_to @vote, class: 'btn btn-pill btn-flat-success btn-large' do
      %span 打开我的议题

  .desc 也可以去看看其他人创建的议题
  .go
    %a.btn.btn-pill.btn-flat-success.btn-large{:href => '/votes'}
      %span 返回议题广场

app/views/votes/edit.html.haml
= render_cell :votes, :form, :vote => @vote, :user => current_user

app/views/votes/index.html.haml
.page-landing{:data => {:nav => :home, :title => '议题大厅'}}
  .topbar
    %a.lucky{:href => url_for([:lucky, :votes])}
      .dice
        .p

  :ruby
    url = '/votes'
    url = '/votes/hot' if action_name == 'hot'

  = render_cell :topics, :list, @votes, current_user, url

app/views/votes/lucky.html.haml
.page-lucky
  .loading-info
    .icon
      %i.fa.fa-circle-o-notch.fa-spin 
    .text 正在推荐下一个议题 …

  .no-next
    .ac
    .text 没有议题可以推荐了 …
    .pls-create
      %span 发起新议题吧！
    .arrow
      %i.fa.fa-arrow-down

app/views/votes/new_common.html.haml
.page-new-topic
  = render_cell :topics, :new_form_topbar

  = form_for @vote, html: {class: 'form'} do |f|
    = render_cell :topics, :new_form_part_tdesc, step_num: 1
    = render_cell :topics, :new_form_part_titems, step_num: 2

app/views/votes/new_shopping.html.haml
.page-new-topic
  = render_cell :topics, :new_form_topbar, step_count: 3

  = form_for @vote, html: {class:'form'} do |f|
    = render_cell :topics, :new_form_part_topenurl, step_num: 1
    = render_cell :topics, :new_form_part_tdesc, step_num: 2
    = render_cell :topics, :new_form_part_titems, step_num: 3

app/views/votes/new_with_weburl_by_infocard.html.haml
.page-new-topic
  .topbar
    %a.back{:href => new_vote_path(kind: 'weburl', category_id: @category.id.to_s)}
      %i.fa.fa-chevron-left
    .steps
      .step.active{:data => {:step => 1}}
        %span 
          .no 1
          %i.fa.fa-check
      .step{:data => {:step => 2}}
        %span 
          .no 2
          %i.fa.fa-check

  = form_for @vote, html: {class:'form'} do |f|
    .part.tdesc{:data => {:step => 1}}
      %input{:name => 'vote[infocard_id]', :value => @infocard.id.to_s, :type => 'hidden'}
      .infocard.product
        .product-logo
          %img{:src => @infocard.logo}
        .data
          .product-name= @infocard.title
          .product-desc= @infocard.desc
      .fields
        %label 请输入议题描述
        %textarea.form-control.tdesc{:placeholder => '有什么事情想知道大家的看法呢？', :rows => 5, name: 'vote[title]'}
      .submits
        %a.next.disabled{:href => 'javascript:;'}
          %span 下一步
          %i.fa.fa-arrow-right

    .part{:style => 'display:none;', :data => {:step => 2}}
      .fields
        %label 请输入预置选项（至少两个）
        .item-inputs
          .ipt
            %input.form-control{:placeholder => '选项 1', name: 'vote[vote_items_attributes][][title]'}
            %a.delete.disabled{:href => 'javascript:;'}
              %i.fa.fa-times
          .ipt
            %input.form-control{:placeholder => '选项 2', name: 'vote[vote_items_attributes][][title]'}
            %a.delete.disabled{:href => 'javascript:;'}
              %i.fa.fa-times
      .submits
        %a.prev{:href => 'javascript:;'}
          %i.fa.fa-arrow-left
          %span 上一步
        %a.additem{:href => 'javascript:;'}
          %i.fa.fa-plus
        .additem-text
          %i.fa.fa-arrow-up
          %span 按这里增加选项
         
        %a.done.disabled{:href => 'javascript:;'}
          %span 完成
          %i.fa.fa-check

app/views/votes/result.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title.text-center 查看讨论进行状态
  .panel-body.text-center
    %h1
      议题：#{@vote.title}
.panel.panel-default
  .panel-body
    - @questions.each do |question|
      .question
        .question-title
          %h4
            讨论要点：#{question.title}
        .answers
          - question.answers.each do |answer|
            - percent = (answer.users.count.to_f / @vote.invite_uids.count * 100).to_i
            .answer-result{"data-id" => "#{answer.id}", "data-target" => "#model-#{answer.id}", "data-toggle" => "modal"}
              .col-xs-1.answer-select
                - if answer.answered_by?(current_user)
                  √
              .col-xs-10.answer-progress
                .progress
                  .progress-bar{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => percent, :role => "progressbar", :style => "width: #{percent}%;"}
                  .answer-result-title
                    = answer.title
              .col-xs-1.answer-percent
                = '%d%' % percent
              .clearfix
      %hr/
- if !@vote.finished? and @vote.user == current_user
  = link_to '发起人修改议题', edit_vote_path(@vote), class: 'btn btn-default btn-block'
- @questions.map(&:answers).flatten.each do |answer|
  .modal.fade{"aria-hidden" => "true", :id => "modal-#{answer.id}", :role => "dialog", :tabindex => "-1"}
    .modal-dialog.modal-sm
      .modal-content
        .modal-body
          %div
            %strong 选项：
            = answer.title
          %div
            %strong 投票人：
            - answer.users.each do |user|
              = user.nickname
              %br/

app/views/votes/search.html.haml
.page-search{:data => {:nav => :search}}
  .topbar
    %i.fa.fa-search
    .ipt
      %input.form-control{:name => :q, :placeholder => '输入搜索词'}
    %a.cancel{:href => 'javascript:;'} 取消

  .search-content
    .history
      %a.clear{:href => 'javascript:;'}
        %i.fa.fa-trash
        %span 清除所有搜索历史

    .result{:style => 'display:none;'}
      - @votes.each do |vote|
        = link_to vote, class: 'topic' do
          .data
            .title
              = vote.title.gsub(Regexp.new(params[:q]), '<span class="key">\0</span>').html_safe
            .stat
              %span
                = "#{vote.vote_items.count} 个选项"
              %span
                = "#{vote.voted_users.count} 人参与"
          .joiner-count= vote.voted_users.count

app/views/votes/show.html.haml
.page-topic{:data => {:id => @vote.id}}
  .so
    .topic-header
      .btns
        %a.next-vote{:href => 'javascript:;'}
          %i.fa.fa-fast-forward

      %h2.title= @vote.title
      = render_cell :topics, :infocard, @vote.infocard

    = render_cell :topics, :topic_options, @vote_items, current_user

    .topic-btns
      .topic-new-option
        :ruby
          if @vote.added_vote_item_by?(current_user)
            klass = 'disabled'
          else
            klass = ''
          end

        %a.new{:href => 'javascript:;', :class => klass}
          .bc-new
            %i.fa.fa-plus
            %span.new 补充选项
          .bc-done
            %span.done 补充过了

      .vote-done
        %a.done.disabled{:href => 'javascript:;'}
          %i.fa.fa-check
          %span 投完了

    .new-option-overlay
      .form{:data => {:url => "/votes/#{@vote.id}/vote_items"}}
        .fields
          %label 补充新选项
          %textarea.form-control{:placeholder => '输入选项内容', :rows => 3}
        .submits
          %a.cancel{:href => 'javascript:;'}
            %i.fa.fa-times
            %span 取消
          %a.ok.disabled{:href => 'javascript:;'}
            %i.fa.fa-check
            %span 确定

  .share-overlay
    .form
      .fields
        %label 分享到 …
        .s 现在是内测阶段，微博应用并没有审核通过，只能添加我们团队的测试用户
        .s 因此即使分享了也没意义，别人登录不进来的
        .s 所以内测期间此功能不开放
      .submits
        %a.cancel{:href => 'javascript:;'}
          %i.fa.fa-times
          %span 取消